version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: academy-courses
        container_name: academy-courses
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - network-app

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - network-app

    db:
        image: mysql
        container_name: academy_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: academy_course
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - dbdata:/var/lib/mysql
        networks:
            - network-app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - network-app

networks:
    network-app:
        driver: bridge

volumes:
    dbdata:
